name: PR

on: pull_request

permissions:
  contents: read

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-markdown:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Lint markdown
        uses: docker://ghcr.io/ponylang/shared-docker-ci-markdownlint:20260810

  lint-shell:
    name: Lint shell scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Lint shell scripts
        uses: docker://ghcr.io/ponylang/shared-docker-ci-shellcheck:20260810

  validate-docker-image-builds:
    name: Validate Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Docker build
        run: "docker build --pull docker/."
